import type { Metadata } from 'next'
import { Oswald } from 'next/font/google'
import '../globals.css'
import StoreProviders from '../store/storeProvider'
import { Navbar } from '@/components/navbars/navbar';

const inter = Oswald({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      <body className={`${inter.className}`}>
        <StoreProviders>
          <Navbar/>
          {children}
        </StoreProviders>
      </body>
    </html>
  )
}
